export const TEMPLATES = [
  {
    id: "minimal",
    name: "Minimal",
    layout: "single",
    headingFont: "'Fraunces', serif",
    bodyFont: "'Inter', sans-serif",
    accent: "#111827",
    headerAlign: "left",
  },
  {
    id: "modern-teal",
    name: "Modern Teal",
    layout: "single",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    accent: "#0f766e",
    headerAlign: "left",
  },
  {
    id: "classic-serif",
    name: "Classic Serif",
    layout: "single",
    headingFont: "'Fraunces', serif",
    bodyFont: "'Fraunces', serif",
    accent: "#78350f",
    headerAlign: "center",
  },
  {
    id: "bold-navy",
    name: "Bold Navy",
    layout: "banner",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    accent: "#1e3a8a",
    headerAlign: "left",
  },
  {
    id: "sidebar-slate",
    name: "Sidebar Slate",
    layout: "sidebar",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    accent: "#334155",
    headerAlign: "left",
  },
  {
    id: "sidebar-emerald",
    name: "Sidebar Emerald",
    layout: "sidebar",
    headingFont: "'Fraunces', serif",
    bodyFont: "'Inter', sans-serif",
    accent: "#065f46",
    headerAlign: "left",
  },
  {
    id: "compact-ats",
    name: "Compact ATS",
    layout: "single",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    accent: "#374151",
    headerAlign: "left",
    compact: true,
  },
  {
    id: "editorial-maroon",
    name: "Editorial",
    layout: "banner",
    headingFont: "'Fraunces', serif",
    bodyFont: "'Fraunces', serif",
    accent: "#7f1d1d",
    headerAlign: "center",
  },
];

export const getTemplateConfig = (id) =>
  TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];